# Disable any logging or output
defaults:
  - main
  - _self_
  - override hydra/job_logging: disabled

device: cpu  # or 'cuda' if you want to run on the GPU

hydra:
  output_subdir: null
  run:
    dir: .
